### ISSUE TITLE
[BUG] Gacha simulator use wrong rate

### ISSUE THREAD

**Issue by dnaroma** [Sekai-World/sekai-viewer#38]
**Describe the bug**

The gacha is supposed to have 2* by 88.5%, 3* by 8.5% and 4* by 3%, but test result divers.

**To Reproduce**

1. Go to gacha list and select a gacha.
2. Click any gacha button for multiple times.
3. The rate displayed divers from the rate supposed.

**Expected behavior**

Use right rate as listed.

**Screenshots**

![](https://media.discordapp.net/attachments/763369173849079808/769804789566406668/Screenshot_2020-10-25-14-08-58-594_org.mozilla.firefox.jpg?width=225&height=500)

**Browser (please complete the following information):**
 - OS: Android
 - Browser Chrome
 - Version ?

**Possible cause and/or solution**

**Comment by Build774** [comment]
I think this is because of 確定枠.  
There seems to be several ways to calculate possibility about this.  
https://keisan.casio.jp/exec/user/1491105652 (Japanese)

So we should find out which formula is appropriate, and decide which probability to use (the result of rolling one shot gacha 10,000,000 times or the result of rolling 10 shot gacha 1,000,000 times).  
In any case, the results will be different between rolling one gacha and rolling 10 shot gacha.

BTW I think `Math.random() * 99 + 1` should be `Math.random() * 100`.

**Comment by dnaroma** [comment]
> I think this is because of 確定枠.

I understand. The listed rate is only for normal draw, in 確定枠 it changes. The test result is the mixed rate of normal draw and 確定枠 draw.

In my opinion the rate listed should have 3 parts: normal, 確定枠 and mixed rate.

**Comment by dnaroma** [comment]
> BTW I think `Math.random() * 99 + 1` should be `Math.random() * 100`.

I want to utilize the random from (0,99) to (1,100) which have 100 intergers, (0,100) have 101.

I don't know if my thought is right. Feel free to correct me.

**Comment by Build774** [comment]
According to [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Math/random), `Math.random()` seems to return `[0, 1)` in floating point number. 
So `Math.random() * 100` becomes `[0, 99.999999999…]`.
When you divide 100% into 5 pieces (20%), `[0…19.9999], [20…39.9999], [40…59.9999], [60…79.9999], [80…99.9999]` will be natural.
Doing `[1…19.9999], [20…39.9999], [40…59.9999], [60…79.9999], [80…99.9999]` will make the probability of the `[1…19.9999]` being chosen low.

**Comment by xfl03** [comment]
In each GACHA * 10，the expected value of 2* is 8.5553, 3* is 1.1359 and 4* is 0.3088. 
The result of your test is 8.5446, 1.1494 and 0.3040. The result is almost correct.
