### ISSUE TITLE
[BUG] Original language not displaying for story reader

### ISSUE THREAD

**Issue by burenai** [Sekai-World/sekai-viewer#454]
Original Japanese language does not display in story reader even if "Original" is selected for "Game Content Display Mode" in the settings.

**To Reproduce**
Go to story reader with "Original" selected for "Game Content Display Mode" in the settings.

**Expected behavior**
Japanese language text would appear in the Story Reader

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 118.0.5993.117 (Official Build) (64-bit)

**Possible cause and/or solution**
I do not know if this is intended or not, but I use the stories here to learn Japanese, so I would hope that there is an option to see Japanese text in the Story Reader. Thank you.

**Comment by dnaroma** [comment]
Can you provide more context, such as screenshots, because I cannot reproduce it

**Comment by Makiori** [comment]
![1](https://github.com/Sekai-World/sekai-viewer/assets/74490475/5068421a-16a3-499d-bb6d-229c3d70f935)
![2](https://github.com/Sekai-World/sekai-viewer/assets/74490475/82b3d506-c560-4f9f-9580-edffa241b985)

**Comment by sstarosz** [comment]
Hi,

I've been trying to look into this problem and I notice that inconsistent language translations in returned from different types of links. It seems to me that this is due to changes on the database.

**For example:**
Link: 
https://sekai.best/storyreader/unitStory/school_refusal/1/6
sends a request for: 
https://storage.sekai.best/sekai-assets/scenario/unitstory/school-refusal-story-chapter_rip/nightcode_01_05.asset
which returns an asset that containe text(TalkData) in English

While the same unit story only in the next chapter: 
https://sekai.best/storyreader/unitStory/school_refusal/1/7
sends a request for: 
https://storage.sekai.best/sekai-assets/scenario/unitstory/school-refusal-story-chapter_rip/nightcode_01_06.asset
and returns text in Japanese

These links refer to the same address, the only differences is the asset number.



The same thing happens in other links from `storyreader/`
**For example:**
`charaStory/` is always in Japanese

`cardStory/` is mixed
https://sekai.best/storyreader/cardStory/1/1/1 - English
https://sekai.best/storyreader/cardStory/1/1/2 - Japanese

`eventStory/` is mostly in English(except for events not available global server), but I managed to find one in Japanese
https://sekai.best/storyreader/eventStory/6/1 - Japanese
https://sekai.best/storyreader/eventStory/6/2 - English


I've tested this on different devices on different web browsers and on different network and in each case the result is the same, I don't see any logic in the code that was referring to different translations depending on the `Game Content Display Mode` setting option in `StoryReaderContent.tsx`, so I'm guessing that previously these `.assets` returned dialogues only in Japanese, and after some changes to the database they suddenly started returning mixed dialogs.

**Comment by dnaroma** [comment]
Thanks for reporting and testing, some English assets came to the Japanese storage by mistake. The correct files are uploaded and now there should be no English in JP region.
